clear_label(addresses=CODE:{0x70030})
mark_data(range=CODE:0x2C903..0x2C9AB, data_type=DataType::Word)
mark_data(range=CODE:0x2C9AB..0x2CAA0, data_type=DataType::Byte)
mark_data(range=CODE:0x37B8F..0x37BC3, data_type=DataType::Byte)
mark_data(range=CODE:0x37BC3..0x37E2A, data_type=DataType::Byte)
mark_data(range=CODE:0x7192C..0x71938, data_type=DataType::Byte)
mark_data(range=CODE:0x71AEB..0x71B13, data_type=DataType::Byte)
mark_data(range=CODE:0x71DC5..0x71DCC, data_type=DataType::Byte)
mark_data(range=CODE:0x724DC..0x724ED, data_type=DataType::Byte)
mark_data(range=CODE:0x72543..0x7254E, data_type=DataType::Byte)
mark_data(range=CODE:0x72667..0x72672, data_type=DataType::Byte)
mark_data(range=CODE:0x726D6..0x726DD, data_type=DataType::Byte)
mark_data(range=CODE:0x726E8..0x72743, data_type=DataType::Byte)
mark_data(range=CODE:0x729CD..0x72A37, data_type=DataType::Byte)
mark_data(range=CODE:0x72E5C..0x72E83, data_type=DataType::Byte)
mark_data(range=CODE:0x72EAA..0x72F0B, data_type=DataType::Byte)
mark_data(range=CODE:0x73D1A..0x73D5A, data_type=DataType::Byte)
mark_data(range=CODE:0x73D5A..0x73DC6, data_type=DataType::Byte)
auto_disassemble(address=CODE:0x267AF)
auto_disassemble(address=CODE:0x26ACC)
auto_disassemble(address=CODE:0x26C02)
auto_disassemble(address=CODE:0x26C94)
auto_disassemble(address=CODE:0x26CAC)
auto_disassemble(address=CODE:0x27321)
auto_disassemble(address=CODE:0x33454)
auto_disassemble(address=CODE:0x71B13)
auto_disassemble(address=CODE:0x71DCC)
auto_disassemble(address=CODE:0x71DCF)
auto_disassemble(address=CODE:0x726CF)
auto_disassemble(address=CODE:0x728B3)
auto_disassemble(address=CODE:0x731D9)
auto_disassemble(address=CODE:0x73280)
auto_disassemble(address=CODE:0x734DD)
auto_disassemble(address=CODE:0x734ED)
auto_disassemble(address=CODE:0x740BF)
auto_disassemble(address=CODE:0x74CBB)
auto_disassemble(address=CODE:0x74D91)
disassemble_range(range=CODE:0x71CE5..0x71CE9, force=True)
disassemble_range(range=CODE:0x72FE8..0x72FE9, force=True)
set_label(address=CODE:0x63F, label="b0_timer0_deferred_work", provisional=False, local=False)
set_label(address=CODE:0x6E5, label="draw_soft_font_cell", provisional=False, local=False)
set_label(address=CODE:0x811, label="load_dptr_indirect", provisional=False, local=False)
set_label(address=CODE:0x1F42, label="int1_comm_handler", provisional=False, local=False)
set_label(address=CODE:0x2011, label="comm1_rx_threshold", provisional=False, local=False)
set_label(address=CODE:0x2039, label="comm2_rx_threshold", provisional=False, local=False)
set_label(address=CODE:0x2061, label="comm3_rx_threshold", provisional=False, local=False)
set_label(address=CODE:0x2089, label="comm1_rx_resume", provisional=False, local=False)
set_label(address=CODE:0x20A1, label="comm2_rx_resume", provisional=False, local=False)
set_label(address=CODE:0x20B9, label="comm3_rx_resume", provisional=False, local=False)
set_label(address=CODE:0x20D1, label="comm1_tx_ready", provisional=False, local=False)
set_label(address=CODE:0x216F, label="comm2_tx_ready", provisional=True, local=False)
set_label(address=CODE:0x22A6, label="comm1_start_tx", provisional=False, local=False)
set_label(address=CODE:0x22CB, label="comm2_start_tx", provisional=False, local=False)
set_label(address=CODE:0x22EC, label="comm3_start_tx", provisional=False, local=False)
set_label(address=CODE:0x231F, label="comm_xoff_threshold", provisional=False, local=False)
set_label(address=CODE:0x2351, label="comm1_flow_settings", provisional=False, local=False)
set_label(address=CODE:0x236E, label="comm2_flow_settings", provisional=False, local=False)
set_label(address=CODE:0x237B, label="comm3_flow_settings", provisional=False, local=False)
set_label(address=CODE:0x23CC, label="main_entry", provisional=False, local=False)
set_label(address=CODE:0x2410, label="boot_wait_loop", provisional=False, local=False)
set_label(address=CODE:0x26B1, label="mark_session_ports_for_tx", provisional=False, local=False)
set_label(address=CODE:0x2779, label="port3_service", provisional=False, local=False)
set_label(address=CODE:0x278C, label="port2_service", provisional=False, local=False)
set_label(address=CODE:0x2796, label="port1_service", provisional=False, local=False)
set_label(address=CODE:0x321D, label="session_rx_byte", provisional=True, local=False)
set_label(address=CODE:0x351B, label="comm_resume_point", provisional=False, local=False)
set_label(address=CODE:0x380A, label="sound_keyclick_bell", provisional=True, local=False)
set_label(address=CODE:0x3AF4, label="nvr_read_block", provisional=False, local=False)
set_label(address=CODE:0x3B27, label="nvr_write_block", provisional=False, local=False)
set_label(address=CODE:0x3BA4, label="nvr_begin_read", provisional=True, local=False)
set_label(address=CODE:0x3BD5, label="i2c_read_byte", provisional=False, local=False)
set_label(address=CODE:0x3BDF, label="i2c_send_control", provisional=False, local=False)
set_label(address=CODE:0x3BE8, label="i2c_write_byte", provisional=False, local=False)
set_label(address=CODE:0x3BF1, label="i2c_read_bit", provisional=False, local=False)
set_label(address=CODE:0x3BFF, label="i2c_write_bit", provisional=False, local=False)
set_label(address=CODE:0x3C0A, label="i2c_stop", provisional=False, local=False)
set_label(address=CODE:0x3C1B, label="i2c_check_bus_and_start", provisional=False, local=False)
set_label(address=CODE:0x3C4A, label="i2c_release", provisional=False, local=False)
set_label(address=CODE:0x8AD9, label="nvr_load_session_settings", provisional=True, local=False)
set_label(address=CODE:0x8C22, label="nvr_save_all", provisional=False, local=False)
set_label(address=CODE:0x8D00, label="nvr_check_all", provisional=False, local=False)
set_label(address=CODE:0x8F5E, label="load_settings_or_defaults", provisional=False, local=False)
set_label(address=CODE:0xAA67, label="post_selftest_init", provisional=False, local=False)
set_label(address=CODE:0xACE8, label="row_descriptor", provisional=True, local=False)
set_label(address=CODE:0xCBA9, label="insert_mode_shift_row", provisional=False, local=False)
set_label(address=CODE:0x2519F, label="b2_session_kbd_buffer_put", provisional=True, local=False)
set_label(address=CODE:0x252C4, label="b2_setup_ctrl_setup_reset", provisional=False, local=False)
set_label(address=CODE:0x25475, label="b2_lookup_local_function", provisional=False, local=False)
set_label(address=CODE:0x267AF, label="b2_local_fn_hold", provisional=True, local=False)
set_label(address=CODE:0x26ACC, label="b2_local_fn_print", provisional=True, local=False)
set_label(address=CODE:0x26AE0, label="b2_local_fn_print_composed", provisional=False, local=False)
set_label(address=CODE:0x26AF5, label="b2_local_fn_toggle_autoprint", provisional=False, local=False)
set_label(address=CODE:0x26C02, label="b2_local_fn_setup", provisional=False, local=False)
set_label(address=CODE:0x26C7F, label="b2_local_fn_hard_reset", provisional=False, local=False)
set_label(address=CODE:0x26C94, label="b2_local_fn_switch_session", provisional=True, local=False)
set_label(address=CODE:0x26CAC, label="b2_switch_session_next", provisional=False, local=False)
set_label(address=CODE:0x26FE5, label="b2_local_fn_session_backward", provisional=False, local=False)
set_label(address=CODE:0x27321, label="b2_local_fn_toggle_split", provisional=True, local=False)
set_label(address=CODE:0x275AC, label="b2_local_fn_break", provisional=False, local=False)
set_label(address=CODE:0x27688, label="b2_local_fn_disconnect", provisional=False, local=False)
set_label(address=CODE:0x27691, label="b2_local_fn_answerback", provisional=False, local=False)
set_label(address=CODE:0x27D83, label="b2_local_fn_clock", provisional=False, local=False)
set_label(address=CODE:0x27D87, label="b2_local_fn_calculator", provisional=False, local=False)
set_label(address=CODE:0x27D8B, label="b2_local_fn_show_charsets", provisional=False, local=False)
set_label(address=CODE:0x27DD7, label="b2_local_fn_screen_saver", provisional=False, local=False)
set_label(address=CODE:0x27DF4, label="b2_local_fn_screen_saver_no_wake", provisional=False, local=False)
set_label(address=CODE:0x2C903, label="b2_local_function_handlers", provisional=False, local=False)
set_label(address=CODE:0x2C9AB, label="b2_local_function_keys", provisional=False, local=False)
set_label(address=CODE:0x2CFE2, label="b2_save_stack_to_xdata", provisional=False, local=False)
set_label(address=CODE:0x2D004, label="b2_restore_stack_from_xdata", provisional=False, local=False)
set_label(address=CODE:0x2D291, label="b2_key_index_to_station", provisional=False, local=False)
set_label(address=CODE:0x2D5C7, label="b2_local_fn_fast_scroll", provisional=False, local=False)
set_label(address=CODE:0x2D608, label="b2_local_fn_slow_scroll", provisional=False, local=False)
set_label(address=CODE:0x2DF4A, label="b2_local_function_numbers", provisional=False, local=False)
set_label(address=CODE:0x3066F, label="b3_blit_char_cells", provisional=True, local=False)
set_label(address=CODE:0x32130, label="screen_saver_tick", provisional=True, local=False)
set_label(address=CODE:0x3220C, label="energy_saver_enter", provisional=False, local=False)
set_label(address=CODE:0x3223F, label="energy_saver_exit", provisional=False, local=False)
set_label(address=CODE:0x33454, label="split_screen_on", provisional=False, local=False)
set_label(address=CODE:0x35912, label="layout_param", provisional=False, local=False)
set_label(address=CODE:0x36A5E, label="layout_window2_title", provisional=False, local=False)
set_label(address=CODE:0x36BED, label="layout_frame_end_row", provisional=False, local=False)
set_label(address=CODE:0x36E98, label="layout_write_row_flags", provisional=False, local=False)
set_label(address=CODE:0x3791F, label="show_selftest_results", provisional=False, local=False)
set_label(address=CODE:0x37946, label="show_error_bits", provisional=False, local=False)
set_label(address=CODE:0x37B04, label="draw_selftest_message", provisional=True, local=False)
set_label(address=CODE:0x37B32, label="point_r1_at_screen_row", provisional=True, local=False)
set_label(address=CODE:0x37B62, label="log_selftest_message", provisional=True, local=False)
set_label(address=CODE:0x37B8F, label="selftest_message_ptrs", provisional=False, local=False)
set_label(address=CODE:0x37BC3, label="selftest_messages", provisional=False, local=False)
set_label(address=CODE:0x51B8C, label="b5_setup_key_dispatch", provisional=False, local=False)
set_label(address=CODE:0x5C06B, label="b5_render_rows", provisional=True, local=False)
set_label(address=CODE:0x61784, label="b6_load_font", provisional=False, local=False)
set_label(address=CODE:0x61846, label="b6_set_font_selects", provisional=False, local=False)
set_label(address=CODE:0x61852, label="b6_unpack_font", provisional=False, local=False)
set_label(address=CODE:0x6198A, label="b6_unpack_glyph", provisional=False, local=False)
set_label(address=CODE:0x6A9FA, label="b6_translate_key", provisional=True, local=False)
set_label(address=CODE:0x70030, label="rom_signature", provisional=False, local=False)
set_label(address=CODE:0x7003A, label="cartridge_found_switch_rom", provisional=False, local=False)
set_label(address=CODE:0x7003E, label="cartridge_checksum_failed", provisional=False, local=False)
set_label(address=CODE:0x70042, label="detect_rom_cartridge", provisional=False, local=False)
set_label(address=CODE:0x70075, label="test_rom_checksums", provisional=False, local=False)
set_label(address=CODE:0x700D7, label="sum_rom_bank", provisional=False, local=False)
set_label(address=CODE:0x70100, label="isr_int0_kbd_frame", provisional=True, local=False)
set_label(address=CODE:0x70534, label="isr_timer0", provisional=False, local=False)
set_label(address=CODE:0x708B5, label="restore_ram_page", provisional=False, local=False)
set_label(address=CODE:0x712FA, label="isr_int1_comm", provisional=False, local=False)
set_label(address=CODE:0x71709, label="b7_comm1_flow_settings", provisional=False, local=False)
set_label(address=CODE:0x71726, label="b7_comm2_flow_settings", provisional=False, local=False)
set_label(address=CODE:0x71733, label="b7_comm3_flow_settings", provisional=False, local=False)
set_label(address=CODE:0x71784, label="blit_fb_copy_up", provisional=False, local=False)
set_label(address=CODE:0x71788, label="blit_fb_copy_down", provisional=False, local=False)
set_label(address=CODE:0x7199C, label="test_comm_ch1_internal", provisional=False, local=False)
set_label(address=CODE:0x719A8, label="test_comm_ch2_internal", provisional=False, local=False)
set_label(address=CODE:0x719B4, label="test_comm_ch3_internal", provisional=False, local=False)
set_label(address=CODE:0x719C0, label="comm_loopback_suite", provisional=False, local=False)
set_label(address=CODE:0x719E4, label="test_comm_ch1_modem_lines_a", provisional=True, local=False)
set_label(address=CODE:0x719FB, label="test_comm_ch1_modem_lines_b", provisional=True, local=False)
set_label(address=CODE:0x71A0B, label="test_comm_ch2_modem_lines", provisional=True, local=False)
set_label(address=CODE:0x71A1B, label="test_comm_ch3_modem_lines", provisional=True, local=False)
set_label(address=CODE:0x71A2B, label="check_modem_line_loopback", provisional=True, local=False)
set_label(address=CODE:0x71A6D, label="set_modem_outputs", provisional=True, local=False)
set_label(address=CODE:0x71A9B, label="test_printer_port_loopback", provisional=True, local=False)
set_label(address=CODE:0x71AEB, label="printer_loopback_table", provisional=True, local=False)
set_label(address=CODE:0x71B13, label="test_printer_port_data", provisional=True, local=False)
set_label(address=CODE:0x71B3B, label="printer_test_failed_halt", provisional=True, local=False)
set_label(address=CODE:0x71B4E, label="printer_test_pattern_55", provisional=True, local=False)
set_label(address=CODE:0x71BA7, label="printer_test_pattern_aa", provisional=True, local=False)
set_label(address=CODE:0x71BC2, label="printer_test_pattern_30", provisional=True, local=False)
set_label(address=CODE:0x71BE3, label="printer_test_pattern_ff", provisional=True, local=False)
set_label(address=CODE:0x71DBF, label="printer_test_setup_regs", provisional=True, local=False)
set_label(address=CODE:0x71F19, label="comm_loop_test_55", provisional=True, local=False)
set_label(address=CODE:0x71F46, label="comm_loop_test_aa", provisional=True, local=False)
set_label(address=CODE:0x71F9E, label="comm_loop_test_interrupt", provisional=True, local=False)
set_label(address=CODE:0x72115, label="comm_loop_test_2115", provisional=True, local=False)
set_label(address=CODE:0x7228C, label="comm_loop_test_228c", provisional=True, local=False)
set_label(address=CODE:0x72362, label="comm_loop_test_format_f3", provisional=True, local=False)
set_label(address=CODE:0x72424, label="comm_loop_test_format_fa", provisional=True, local=False)
set_label(address=CODE:0x7246C, label="comm_loop_test_formats", provisional=True, local=False)
set_label(address=CODE:0x724DC, label="comm_format_table", provisional=True, local=False)
set_label(address=CODE:0x724ED, label="comm_loop_test_baud_sweep", provisional=True, local=False)
set_label(address=CODE:0x72543, label="comm_baud_sweep_table", provisional=True, local=False)
set_label(address=CODE:0x7254E, label="comm_select_channel_defaults", provisional=True, local=False)
set_label(address=CODE:0x7256A, label="comm_program_channel", provisional=True, local=False)
set_label(address=CODE:0x7262B, label="comm_send_and_wait", provisional=False, local=False)
set_label(address=CODE:0x72672, label="comm_receive_byte", provisional=False, local=False)
set_label(address=CODE:0x726AA, label="set_ch1_modem_ctl", provisional=True, local=False)
set_label(address=CODE:0x726B5, label="set_ch2_modem_ctl", provisional=True, local=False)
set_label(address=CODE:0x726C2, label="set_ch3_modem_ctl", provisional=True, local=False)
set_label(address=CODE:0x726CF, label="printer_port_init", provisional=True, local=False)
set_label(address=CODE:0x726DD, label="comm_load_test_regs", provisional=True, local=False)
set_label(address=CODE:0x726E8, label="comm_test_reg_table", provisional=True, local=False)
set_label(address=CODE:0x72743, label="kbd_reset_and_identify", provisional=False, local=False)
set_label(address=CODE:0x727A8, label="kbd_line_loopback_test", provisional=True, local=False)
set_label(address=CODE:0x72800, label="kbd_wait_bat", provisional=True, local=False)
set_label(address=CODE:0x7286B, label="kbd_send_cmd", provisional=False, local=False)
set_label(address=CODE:0x7288D, label="kbd_recv_byte", provisional=False, local=False)
set_label(address=CODE:0x728B3, label="kbd_interface_reset_line_low", provisional=True, local=False)
set_label(address=CODE:0x728B6, label="kbd_interface_reset", provisional=False, local=False)
set_label(address=CODE:0x728CB, label="ram_block_present", provisional=True, local=False)
set_label(address=CODE:0x728EA, label="dma_sweep_init", provisional=True, local=False)
set_label(address=CODE:0x72900, label="dma_src_add_2000", provisional=False, local=False)
set_label(address=CODE:0x7290B, label="dma_dst_add_2000", provisional=False, local=False)
set_label(address=CODE:0x72916, label="dma_src_add_8000", provisional=False, local=False)
set_label(address=CODE:0x72921, label="dma_dst_add_8000", provisional=False, local=False)
set_label(address=CODE:0x7292C, label="dma_src_skip_blocks", provisional=True, local=False)
set_label(address=CODE:0x72937, label="dma_sweep_all_ram", provisional=True, local=False)
set_label(address=CODE:0x7299F, label="dma_table_load_entry", provisional=False, local=False)
set_label(address=CODE:0x729CD, label="dma_test_table", provisional=False, local=False)
set_label(address=CODE:0x72A37, label="paged_copy_forward", provisional=True, local=False)
set_label(address=CODE:0x72A86, label="paged_copy_backward", provisional=True, local=False)
set_label(address=CODE:0x72AD8, label="dma_start_cmd03", provisional=True, local=False)
set_label(address=CODE:0x72ADC, label="dma_start_cmd13", provisional=True, local=False)
set_label(address=CODE:0x72AE0, label="blit_copy", provisional=True, local=False)
set_label(address=CODE:0x72B5F, label="dma_start_live_only", provisional=True, local=False)
set_label(address=CODE:0x72BA3, label="dma_prime_page0", provisional=True, local=False)
set_label(address=CODE:0x72BBA, label="dma_clear_ram", provisional=True, local=False)
set_label(address=CODE:0x72C01, label="clear_xdata_0000_00ff", provisional=False, local=False)
set_label(address=CODE:0x72C0D, label="reset_entry", provisional=False, local=False)
set_label(address=CODE:0x72C14, label="reset_entry_alt", provisional=True, local=False)
set_label(address=CODE:0x72C1A, label="selftest_start", provisional=False, local=False)
set_label(address=CODE:0x72C64, label="test_internal_ram", provisional=False, local=False)
set_label(address=CODE:0x72C90, label="internal_ram_failed", provisional=False, local=False)
set_label(address=CODE:0x72CB4, label="internal_ram_ok", provisional=False, local=False)
set_label(address=CODE:0x72CE4, label="selftest_keyboard", provisional=False, local=False)
set_label(address=CODE:0x72D1D, label="select_factory_test_set", provisional=True, local=False)
set_label(address=CODE:0x72D26, label="selftest_rom", provisional=False, local=False)
set_label(address=CODE:0x72D39, label="selftest_ram", provisional=False, local=False)
set_label(address=CODE:0x72D47, label="selftest_hw_setup", provisional=True, local=False)
set_label(address=CODE:0x72DA1, label="crt_set_v_centre", provisional=False, local=False)
set_label(address=CODE:0x72DD2, label="crt_set_rotation", provisional=False, local=False)
set_label(address=CODE:0x72DF5, label="crt_set_h_centre", provisional=False, local=False)
set_label(address=CODE:0x72E13, label="video_power_on_pulse", provisional=True, local=False)
set_label(address=CODE:0x72E37, label="set_video_timing", provisional=True, local=False)
set_label(address=CODE:0x72E5C, label="video_timing_tables", provisional=True, local=False)
set_label(address=CODE:0x72E83, label="load_reg_table", provisional=False, local=False)
set_label(address=CODE:0x72EAA, label="hw_reg_init_table", provisional=False, local=False)
set_label(address=CODE:0x72F0B, label="test_ram", provisional=False, local=False)
set_label(address=CODE:0x72F61, label="fill_page0_head_ff", provisional=False, local=False)
set_label(address=CODE:0x72F7F, label="fill_page0_head_00", provisional=False, local=False)
set_label(address=CODE:0x72F94, label="clear_xdata_7e00", provisional=False, local=False)
set_label(address=CODE:0x72F9F, label="test_dma", provisional=True, local=False)
set_label(address=CODE:0x72FED, label="test_ram_data_bus", provisional=False, local=False)
set_label(address=CODE:0x73029, label="test_ram_address_bus", provisional=False, local=False)
set_label(address=CODE:0x73050, label="dptr_shift_left", provisional=False, local=False)
set_label(address=CODE:0x7305C, label="probe_ram_bank", provisional=False, local=False)
set_label(address=CODE:0x730F1, label="require_large_bank0", provisional=True, local=False)
set_label(address=CODE:0x730F6, label="decode_ram_config", provisional=False, local=False)
set_label(address=CODE:0x73178, label="ram_bank0_is_small", provisional=True, local=False)
set_label(address=CODE:0x7317C, label="write_addr_line_pattern", provisional=False, local=False)
set_label(address=CODE:0x73194, label="verify_addr_line_pattern", provisional=False, local=False)
set_label(address=CODE:0x731B3, label="write_page_pattern", provisional=False, local=False)
set_label(address=CODE:0x731C6, label="verify_page_pattern", provisional=False, local=False)
set_label(address=CODE:0x731D9, label="test_all_ram_pages", provisional=True, local=False)
set_label(address=CODE:0x73280, label="test_low_windows", provisional=True, local=False)
set_label(address=CODE:0x7328E, label="test_low_windows_02aa", provisional=True, local=False)
set_label(address=CODE:0x73375, label="write_stride_pattern", provisional=False, local=False)
set_label(address=CODE:0x73383, label="verify_stride_pattern", provisional=False, local=False)
set_label(address=CODE:0x73397, label="test_low_windows_0555", provisional=True, local=False)
set_label(address=CODE:0x734CF, label="save_ram_config", provisional=False, local=False)
set_label(address=CODE:0x734DD, label="load_ram_config", provisional=False, local=False)
set_label(address=CODE:0x734ED, label="clear_xdata_0000_7eff", provisional=False, local=False)
set_label(address=CODE:0x734FF, label="init_without_selftest", provisional=True, local=False)
set_label(address=CODE:0x73521, label="selftest_finish_no_errors", provisional=True, local=False)
set_label(address=CODE:0x7352D, label="selftest_finish", provisional=False, local=False)
set_label(address=CODE:0x73A9E, label="comm_reg2_set", provisional=True, local=False)
set_label(address=CODE:0x73AA2, label="comm_reg2_clear", provisional=True, local=False)
set_label(address=CODE:0x73B24, label="video_init", provisional=True, local=False)
set_label(address=CODE:0x73B70, label="video_set_mode_and_clear", provisional=True, local=False)
set_label(address=CODE:0x73C32, label="video_fill_block", provisional=True, local=False)
set_label(address=CODE:0x73D1A, label="video_reg_tables", provisional=True, local=False)
set_label(address=CODE:0x73D5A, label="bit_mask_tables", provisional=True, local=False)
set_label(address=CODE:0x73DC6, label="delay_n_x100", provisional=False, local=False)
set_label(address=CODE:0x73DD1, label="delay_100", provisional=False, local=False)
set_label(address=CODE:0x73DD9, label="delay_8", provisional=False, local=False)
set_label(address=CODE:0x73DDD, label="delay_31", provisional=False, local=False)
set_label(address=CODE:0x73DE1, label="delay_14", provisional=False, local=False)
set_label(address=CODE:0x73DE5, label="delay_2", provisional=False, local=False)
set_label(address=CODE:0x73DE7, label="delay_a", provisional=False, local=False)
set_label(address=CODE:0x740BF, label="calc_key_dispatch", provisional=False, local=False)
set_label(address=CODE:0x74CBB, label="calc_move_left", provisional=False, local=False)
set_label(address=CODE:0x74D91, label="calc_move_right", provisional=False, local=False)
set_label(address=CODE:0x756BD, label="draw_cell_at_column", provisional=False, local=False)
set_label(address=CODE:0x7ABDC, label="factory_loopback_mode", provisional=True, local=False)
set_label(address=CODE:0x7AD1A, label="factory_command_table", provisional=False, local=False)
set_label(address=CODE:0x7AFB9, label="setup_char_blit_for_row", provisional=True, local=False)
set_label(address=CODE:0x7B123, label="retest_ram_and_dma", provisional=False, local=False)
set_label(address=CODE:0x7B488, label="script_rerun_selftest", provisional=True, local=False)
set_label(address=CODE:0x7B786, label="selftest_fail", provisional=False, local=False)
set_label(address=CODE:0x7B793, label="selftest_fatal", provisional=False, local=False)
set_label(address=CODE:0x7B799, label="blink_error_code_on_leds", provisional=False, local=False)
set_label(address=CODE:0x7B7C6, label="selftest_next_group", provisional=False, local=False)
set_label(address=CODE:0x7B80F, label="kbd_set_leds", provisional=False, local=False)
set_label(address=CODE:0x7B828, label="report_error_on_printer_port", provisional=True, local=False)
set_label(address=CODE:0x7B852, label="init_timers", provisional=True, local=False)
set_note(address=CODE:0x7352D..0x735FE, note=Note(id="0000000000000GCKQJN9BDWBFP", content=r#"Test-select bits that selftest_finish checks:
B.1 test_comm_ch1_internal; B.2 test_comm_ch1_modem_lines_a; 0x74.6 test_comm_ch1_modem_lines_b; B.4 test_comm_ch2_internal; B.5 test_comm_ch2_modem_lines; 0x74.4 test_comm_ch3_internal; 0x74.5 test_comm_ch3_modem_lines; 0x74.7 test_printer_port_loopback.
Power-up (B=0x52, 0x74=0x10) runs the internal loopback tests on all three channels. Factory mode (B=0xB6, 0x74=0xF0) adds the tests that need an external loopback plug: modem lines and printer port.
If B.0 is set (re-run from reset_entry_alt), B.6 toggles and the tests run a second pass through selftest_start. B.3 jumps to selftest_finish_no_errors."#, tags=["selftest"], fields={}, links=[]))
set_note(address=CODE:0x5C5..0x5E4, note=Note(id="0000000000000GWB59R4PKJAJJ", content="Timer 0 work: comm1 receive threshold. When live 0x7FF5 bit 4 is set (unread receive data reached the threshold), write 0x10 to clear it, set 0x74C6, and if port setting 0x2C00 bit 0 (receive XON/XOFF) is on, request XOFF (IDATA 0x0D bit 6) and start transmit. comm2 follows at 0x5E4 (0x7F9B).", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x71A9B..0x71B4E, note=Note(id="0000000000000H2EQJERPBJNZY", content=r#"Parallel printer port. 0x7F2D = control out (bit 0 = strobe), 0x7F2F = data out, 0x7FAE bits 0-4 = status in, 0x7F2E written with 0x20 to idle. test_printer_port_loopback walks printer_loopback_table (control|0x80, data, expected status) and needs a loopback plug. It fails into 0x59 bit 0, and also if P3.3 (INT1) is low at the end.
test_printer_port_data (no caller found in bank 7) writes patterns 0x55/0xAA/0x30/0xFF through 0x7F2A/0x7F2B as well. On failure it sets 0x59 bit 2, calls far_b3_791F and halts."#, tags=["printer", "selftest"], fields={}, links=[]))
set_note(address=CODE:0x72AE0..0x72B60, note=Note(id="0000000000000HAFZK52TTRM94", content="DRAM copy blit: writes all of 0x7F40-0x7F47 (source DPTR/IDATA 0x7E, destination R3/R4/0x7D, size R1/R2), then command 0x13 (0x03 when bit 0x3C). The glyph renderers never rewrite 0x7F42/0x7F45 (and the Screen alignment text never rewrites 0x7F41), so those keep this routine's last values: 0x05 after boot, 0x07 after a double-width line setup, 0x04/0xFC in Set-Up alignment.", tags=["blitter", "video"], fields={}, links=[]))
set_note(address=CODE:0x36E98..0x36E99, note=Note(id="0000000000000J3W4ANDG5DCMQ", content="Writes line-table flag A for the current row (ORL R0,#0x40 moves R0 from the value column to the flag column), then advances R0. Clears flag bits 5-3 unless bit 0x4A (framed windows) is set. Flags: 7 = window 2 (0x7F3C-0x7F3E), 6 = trailing row after frames (layout_frame_end_row), 5 = line along the row's top, 4 = line along its bottom, 3 = inside a frame.", tags=[], fields={}, links=[]))
set_note(address=CODE:0x26B1..0x26DE, note=Note(id="0000000000000JN0FVQ5NAHZKJ", content="Main loop step (bank 0 0x2508, when bit 0x16 is set). For each session s = 1..4 with IDATA 0x69+s non-zero (keyboard data waiting), it reads the session's port from session base + 0x0B (bits 1-0) and sets bit (s-1) in IDATA 0x4F+port. port1_service/port2_service/port3_service then feed that session's data to the port.", tags=["comm", "keyboard"], fields={}, links=[]))
set_note(address=CODE:0x70AEA..0x70D3A, note=Note(id="0000000000000K0S52XT83TPZR", content=r#"Outgoing cross-bank stubs. Each stub is CLR P1.6 (bank 7 -> bank 3); LCALL <self>; SETB P1.6; RET. After the CLR, the CPU fetches the LCALL at the same address in bank 3, and many of those land in bank 3's own stub table, which forwards again (usually to bank 0).
Labels far_bN_XXXX name the final bank and address. scratchpad xbank.py resolves them. Incoming calls from banks 4/5/6 land on LCALLs in bank 7's table at 0x0E72 + 12k (the 68 roots added to this database)."#, tags=["banking"], fields={}, links=[]))
set_note(address=CODE:0x1F42..0x2011, note=Note(id="0000000000000KHX9QM5G16MM1", content=r#"INT1: comm interrupts for all three channels. For each channel it reads the live +5 register (0x7FF0, 0x7F95, 0x7FE5). Bit 1: modem-line change (comm1_modem_change), then writes the result to +6. Bit 2: line event (comm1_line_event). Bit 3: transmitter empty (comm1_tx_ready / comm2_tx_ready / ...). Then it writes +5 = IDATA 0x0D/0x0E/0x0F & 0x0F (interrupt enable, bit 3 = transmit) and +0xA = 0x06.
The emulator asserts INT1 while a channel has +5 bit 3 enabled and an idle transmitter."#, tags=["comm", "hw", "interrupt"], fields={}, links=[]))
set_note(address=CODE:0x27DF4..0x27E15, note=Note(id="0000000000000KM57G0GHWEG55", content=r#"Undocumented local function 60: the same as function 61 (screen saver now, XDATA 0x735F = 1) but it also sets XDATA 0x74D3 = 1. The saver loop (bank 3 0x32181, 0x321F3, 0x322F3) then ignores received host data even when Host wake-up (DECHWUM, 0x7012 bit 5) is on, so only a key restores the screen. 0x74D3 is cleared when the saver exits (0x321D9). Reachable only by DECPFK (e.g. DCS " x 112/1/60 ST binds F1)."#, tags=["hidden", "keyboard"], fields={}, links=[]))
set_note(address=CODE:0x2089..0x20D1, note=Note(id="0000000000000KWDPGYCNPH68T", content="INT1 cause +5 bit 2: the unread receive count drained to the resume point (0x7F59 / 0x7F17 / 0x7F58, 16-byte units). Requests XON (IDATA 0x0D |= 0x88) and reasserts DTR, then returns the XOFF threshold for +6 (comm_xoff_threshold). Previously labelled comm1_line_event. 0x20A1 / 0x20B9 are the comm2 / comm3 copies.", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x331E0..0x33264, note=Note(id="0000000000000M22BK56EDVKQD", content="Window command dispatcher. Local-function handlers queue commands as bits in XDATA 0x7379 (with bit 0x2D); 0x33226 moves them to 0x737A. Each set bit n runs entry n+1 of the table at 0x33254 (little-endian words, R2 = 1..8): entry 6 = 0x33454 split screen on (second session from 0x74D6, sets bit 0x49, IDATA 0x46 = upper << 4 | lower), entry 7 = 0x334C0 (split off?). Split is requested by 0x27465 (Ctrl+F4 on LK, Ctrl+Caps Lock+KP0 on PC, local function 0x4D at 0x27321).", tags=["session", "video"], fields={}, links=[]))
set_note(address=CODE:0x72E83..0x72EAA, note=Note(id="0000000000000MPM46037KT7GB", content=r#"Register staging model. The 0x7F00-0x7F7F half of the register page looks like a staging copy, and 0x7F80-0x7FFF is the live copy. Most writes go to both halves.
load_reg_table entries are (reg, group, value). With group 0 the value goes to both reg and reg^0x80. With a non-zero group, only the staging copy is written and the group bits are ORed into IDATA 0x6E. The INT0 frame handler then copies the staged registers to the live half during retrace and clears 0x6E. Callers wait for 0x6E to reach 0. Groups seen: 0x01 = 0x7F31/0x7F35, 0x02 = 0x7F38-0x7F3A, 0x08 = 0x7F4A-0x7F4C, 0x10 = video timing 0x7F50/52 and 0x7F24-0x7F27."#, tags=["hw"], fields={}, links=[]))
set_note(address=CODE:0x2011..0x2039, note=Note(id="0000000000000MV4H9WGHW6H9N", content="INT1 cause +5 bit 1: the channel's unread receive count reached the XOFF threshold in +6 (16-byte units). Sends XOFF (IDATA 0x0D bits 6/2/3) when receive XON/XOFF is on (B.1), drops DTR through IDATA 0x6F when receive DTR flow is on (B.2). Returns the next +6 value: 0x38 (896, the manual's second threshold) after the first XOFF, 0 after the second. Previously labelled comm1_modem_change. 0x2039 / 0x2061 are the comm2 / comm3 copies.", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x71709..0x71726, note=Note(id="0000000000000N4XMYCD7JDVYN", content="Bank 7 copy of comm1_flow_settings (bank 0 0x2351): B.1 = port+0 bit 0 (receive XON/XOFF), B.2 = port+0 bit 1 (receive DTR), B.3 = port+2 bit 0 (threshold High). 0x2C00 is the comm1 settings block in RAM; the doubled reads are the normal pipelined-read pattern. sub_1726 and sub_1733 are the comm2/comm3 copies.", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x36A83..0x36A84, note=Note(id="0000000000000NJB3CG1Y614XQ", content="Framed split: the line between window 1 and window 2's title bar. Per-session bit 0 of table 0x0E26 picks either bit 4 (line below) on the row two back (window 1's last row) or bit 5 (line above) on the title row itself. Both draw the same line, which is how bits 4/5 were identified.", tags=[], fields={}, links=[]))
set_note(address=CODE:0x7AFB9..0x7B00A, note=Note(id="0000000000000NMCYZMZC6WRM2", content=r#"Set up a character blit (command 0x9C) for row R6. The line-table entry for the row (0x7E00 or 0x7E80, picked by 0x7F31 bit 1) goes to 0x7F44, the destination y in pairs of scan lines (row r = 8r means scan line 16r). 0x7F46 = 0xFF, or 0xFE for double width: 0x100 - value = width in bytes. 0x7F47 = 0xF0/0xF6/0xF8 by video mode (0x08D5): 0x100 - value = glyph height 16/10/8. 0x7F4E = rendition from 0x08D6.
The 0x9C blit itself takes the character code in 0x7F40, the font base in 0x7F41/0x7F42 (0x04 = linear 0x20000), and the destination column in 0x7F43. The hardware looks up the glyph from the character code. 0x9C and 0x9E write a separate framebuffer, not the DRAM holding the font. video_init's 0x9E clears would otherwise wipe font page 2."#, tags=["blitter", "video"], fields={}, links=[]))
set_note(address=CODE:0x72EAA..0x72F0B, note=Note(id="0000000000000P8PBQ84QS7N5H", content="Register init table. reset_entry walks it with P2=0x7F. Each entry is 3 bytes: register low byte (the full address is 0x7Fxx), an unused middle byte, and the value. A 0x00 byte ends the table. The middle byte is 0x10, 0x08, 0x02, 0x01 or 0x00 and may be a leftover mask or group ID.", tags=["hw"], fields={}, links=[]))
set_note(address=CODE:0xBEA0..0xBF93, note=Note(id="0000000000000PJEC8C1TRVQ9N", content="Per-window video format. Two register blocks like the VT420's per-session 0x7FF3/0x7FF4: window 1 = 0x7F38-0x7F3A (frame group 0x02), window 2 = 0x7F3C-0x7F3E (group 0x04); bits 0x49/0x4A and sub_B3_59D1 pick the block. +0 (0xBEA0): row height - 1 from table 0xBEE7 (F/9/7), bit 4 = 132 columns (bit 0x78), bit 5 = Set-Up (bit 0x20 or 0x62), bit 6 = reverse screen (session byte +3 bit 4). +1 (0xBEED): 5 normally, 6 with Overscan (XDATA 0x7004 bit 5, via sub_BF93), 4 with reverse screen. +2 (0xBF63): 0x02 | (bit 0x62 or session byte +0x11 bit 7).", tags=["video"], fields={}, links=[]))
set_note(address=CODE:0x73867..0x73875, note=Note(id="0000000000000PRCT3HZSS4Q23", content="Comm port programming (after Set-Up changes). +0 mode: bit 0 = 8 bits, bit 1 = 2 stop bits, bit 4 = parity, bit 2 = odd, bit 3 = stick (mark 0x1D, space 0x19), bit 5 = loopback. +1 speed: high nibble receive, low nibble transmit; 0 = 300, 1 = 600, 2 = 1200, 3 = 2400, 4 = 4800, 5 = 9600, 6 = 19.2K, 7 = 38.4K, 8 = 57.6K, 9 = 76.8K, A = 115.2K. +2 (0x73AAA) goes 0x00 before and 0x03 after. +4 (0x738EB) = 0x78, bit 7 = parity checked, bit 1 = transmit flow control None/DSR.", tags=["comm", "setup"], fields={}, links=[]))
set_note(address=CODE:0xCBA9..0xCC22, note=Note(id="0000000000000PYANGDAVXCK6B", content="Insert mode (IRM, bit 0x72): called from the character store (0xCB36) before a character is written. Shifts the rest of the row's attribute/character pairs right in DRAM with a descending copy (0x03), then, when bit 0x5E is set (row on screen), shifts the row's pixels right with framebuffer copy 0x8D (bank 7 0x71788): source column in 0x7F40, source scan line 0x7F41 | 0x7F42 << 8, destination column/row in 0x7F43/0x7F44. 0xCC22 is the shift-left counterpart (0x13 + 0x9D).", tags=["blitter", "video", "vt"], fields={}, links=[]))
set_note(address=CODE:0x25475..0x254D7, note=Note(id="0000000000000Q9DK085552SES", content="Local function lookup. R1 = internal key index; 0x2CC78 converts indexes below 0x73 to key station numbers (IBM numbering: F1 0x70, F3 0x72, F12 0x7B, Print Screen 0x7C, Pause 0x7E, Num Lock 0x5A, KP0 0x63, KP1 0x5D, KP2 0x62, KP3 0x67, KP4 0x5C) through the table at 0xD291. B = modifiers (IDATA 0x21 & 7: bit 0 Shift, bit 1 Alt, bit 2 Ctrl). Bit 0x12 set = PC keyboard. Tables: 0xCA10 VT keyboard F1-F5; 0xC9AB PC keyboard with Caps Lock (Print Screen = Set-Up, Pause = Break, Num Lock = VT/IBM toggle); 0xC9BD PC keyboard plain; 0xCA5C/0xCA56, 0xC9DC and 0xCA8A/0xCA87 for the other 0x42 modes. Entries are (station, modifiers, internal function), ending with 0xFF. C set = found, A = internal function, which indexes the handler table 0xC903 (called at 0x24B8D). Internal function k is manual function (Table 8-6, DECPFK) b2_local_function_numbers[k]. Every default entry matches the manual.", tags=["keyboard"], fields={}, links=[]))
set_note(address=CODE:0x624..0x66F, note=Note(id="0000000000000QBM07FEF8BBHS", content="Timer 0 deferred work (in every bank's shared area). When bit 0x29 is clear, the ISR sets it, pushes 0x063F as a fake return address and executes RETI. That ends the interrupt level and runs b0_timer0_deferred_work with other interrupts allowed. It stores the 0x740F read in 0x7410, switches to register bank 2, and hangs if SP >= 0xDF (stack overflow guard). It then runs the periodic tasks (bank 3:0x2C83, 0x2328, bank 2:0x479E, 0x380A), clears 0x29, sets 0x28, pops the ISR's saved registers and RETs to the interrupted code.", tags=["isr"], fields={}, links=[]))
set_note(address=CODE:0x2DF4A..0x2DF9F, note=Note(id="0000000000000QGE673XFCSEYX", content="Internal local function index -> manual function number (VT520 manual Table 8-6, used by DECPFK/DECPAK). 84 entries ending with 0xFF: 0 none, 1-5 Hold/Print/Set-Up/Session fwd/Break, 6 -> 7 hard reset, 7 -> 8 autoprint, 8 -> 9 disconnect, 9 -> 10 answerback, 10 -> 11 print composed, 11 -> 12 session back, ... 38 -> 60, 39 -> 61 screen saver, 40-42 -> 62-64 calculator/clock/charsets, 70 -> 142 slow scroll, 71 -> 144 fast scroll, 77 -> 171 window configuration, 80-83 -> 181-184 session 1-4. Two numbers are not in the manual: 60 (b2_local_fn_screen_saver_no_wake) and 144 (the manual lists Fast Scroll as 143, which DECPFK rejects). DECPFK translation verified in the emulator: 60 -> 0x27DF4, 61 -> 0x27DD7, 144 -> 0x2D5C7.", tags=["keyboard"], fields={}, links=[]))
set_note(address=CODE:0x72AD8..0x72BA3, note=Note(id="0000000000000QHAW67AZDVV18", content=r#"DMA / block-move engine at 0x7F40-0x7F49 (live copy at 0x7FC0-0x7FC9).
0x40/0x41/0x42: source address, split as A[6:0], A[14:7], A[22:15]. 0x43/0x44/0x45: destination address, same split. 0x46/0x47: byte count as a 16-bit two's-complement negative (0 - count).
0x49: command. 0x13 is the normal command. 0x03 when bit 0x3C is set (dma_start_cmd03), which may be a fill or a different direction.
P1.0 is the ready flag: every start spins on JNB P1.0 before writing the command register.
dma_start_live_only writes only the 0x7FCx copy."#, tags=["dma", "hw"], fields={}, links=[]))
set_note(address=CODE:0x2410..0x2474, note=Note(id="0000000000000QX4K8TJR5FD7X", content="Idle loop after the self-test screen. Services ports 1-3 (IDATA 0x50-0x52), polls XDATA 0x7004 bit 4, and runs sub_334B on frame events (bit 0x28). Exits to 0x2474 when bit 0x21 is set (Set-Up requested, b2_local_fn_setup) or to 0x2477 when bit 0x2F is set (any ordinary key, set at bank 2 0x7D80). 0x2477 sets bit 0x22 (normal operation).", tags=["main"], fields={}, links=[]))
set_note(address=CODE:0x252C4..0x252E7, note=Note(id="0000000000000QZFR68JF4B4SS", content="Ctrl + Set-Up key inside Set-Up (bit 0x20) jumps to the power-up reset entry: Ctrl+F3 on the VT keyboard (or PC keyboard without 0x42 bit 7), Ctrl+Caps Lock+Print Screen on the PC keyboard. Documented in the manual (Set-Up chapter).", tags=["keyboard"], fields={}, links=[]))
set_note(address=CODE:0x7AD1A..0x7AD50, note=Note(id="0000000000000R8GTHFWGEJ408", content="Factory command table: (character, handler low, handler high), 0xFF ends. '3'/'4' set/clear bit 0x4A. 'D'-'G' play tones: 0x7F34 = 0x5B, 0x44, 0x3D, 0x37 (pitch), 0x7F33 = 0xD0, delay, 0x50. 'I' (0x7ADA5) moves 0x7F52 toward 0x80, 'J' (0x7ADD8) ramps it up, 'K' (0x7ADF3) ramps it down, 0x10 per frame. 'L' (0x7AE0F) sets 0x7012 bit 5 and runs the screen saver (b3 0x21DE).", tags=["crt", "factory"], fields={}, links=[]))
set_note(address=CODE:0x369D6..0x369D7, note=Note(id="0000000000000RGZFN09TWDGVY", content="Unframed split: sets flag bit 5 (line along the top) on the row at scan line 0x7200 / row height, window 2's first row. The split divider (the VT420 row table flag 0x02).", tags=[], fields={}, links=[]))
set_note(address=CODE:0xD26D..0xD297, note=Note(id="0000000000000RXHQ1S86E3EH2", content="Line size escape handlers: ESC # 5 -> R1 = 0x00 (0xD26D), ESC # 3 -> 0x03 (0xD28D), ESC # 4 -> 0x07 (0xD291), ESC # 6 -> 0x02 (0xD295). sub_D277 stores R1 in the current row's rendition byte (table at IDATA 0x4D/0x4E, via sub_AD1C). The value is a bitmask used as 0x7F4E: bit 0 double height, bit 1 double width, bit 2 bottom half.", tags=["video", "vt"], fields={}, links=[]))
set_note(address=CODE:0x26C02..0x26C80, note=Note(id="0000000000000SVQH6PM73V0FM", content="Set-Up local function (handler 3 in table 0xC903). On key down (bit 0x0D) with no Set-Up already requested it sets 0x734B (0 if in normal operation, 1 if not), calls sub_26B1D and sets bit 0x21, which enters Set-Up. F3 reaches it on most keyboard tables.", tags=["keyboard", "setup"], fields={}, links=[]))
set_note(address=CODE:0x72DA1..0x72E13, note=Note(id="0000000000000T7B1FHNQXCD2R", content="CRT geometry, set from Set-Up > Display > Screen alignment (bank 5 0x5A9C2: Shift+arrows centre, Ctrl+Left/Right rotate). 0x72DA1: vertical centring, 0x7F52 bits 3-0 = 15 - clamp(XDATA 0x7002 - 0x16, 0, 15). 0x72DD2: rotation, 0x7F52 bits 7-4 = XDATA 0x7001 bits 7-4. 0x72DF5: horizontal centring, A = XDATA 0x7003 + 0x15, 0x7F50 = (A / 11) << 4 | (A % 11). All group 0x10 (applied at the next frame). Defaults 0x7F50 = 0x47, 0x7F52 = 0x88.", tags=["crt", "video"], fields={}, links=[]))
set_note(address=CODE:0x719C0..0x719E4, note=Note(id="0000000000000TV7V71T1A6ZQY", content=r#"Comm channels. R3 selects the channel. Channel 1 = block at 0x7F6B, channel 2 = block at 0x7F10, channel 3 = block at 0x7F60. Channel 2's block is one byte longer: command at +0xB (0x7F1B) and modem control at +0xA (0x7F1A). Channels 1 and 3 have command at +0xA and modem control at +9.
comm_loopback_suite loads comm_test_reg_table, then runs: baud sweep, 0x55 and 0xAA loopback, interrupt test (polls P3.3 = INT1), and several format and baud tests. Any failure sets PSW.5. B.6 skips most of the suite.
check_modem_line_loopback drives the modem control outputs and reads them back from the same register in the live half. That needs an external loopback plug."#, tags=["comm", "selftest"], fields={}, links=[]))
set_note(address=CODE:0x61784..0x617D9, note=Note(id="0000000000000TY998CH0ZGVQH", content="Load a font for session IDATA 0x77. R5 -> IDATA 0x74 = font part: 0 = the main 8-column font (256 glyphs), 0x40 = the session's 16-column alternate font (512 glyphs: Latin-2, Hebrew, Greek, DEC Technical, Cyrillic, PC CP437 symbols, box and line pieces). In a WYSE emulation (per-session bit 0x62) the alternate part goes through 0x61A9F instead and holds a PC (CP437-layout) font in both halves. Seen at run time: boot loads R5 = 0 and 0x40 per session; DECCOLM reloads both.", tags=["font"], fields={}, links=[]))
set_note(address=CODE:0x7B786..0x7B852, note=Note(id="0000000000000V0CQ6MA4JFKJH", content=r#"Error reporting. selftest_fail retries a failed group (0x76 counts down from 3, set by selftest_next_group) when B.6 is set. Otherwise selftest_fatal takes over.
Normal mode: blink_error_code_on_leds loops forever. It shows the 0x77 high nibble on the keyboard LEDs (PS/2 0xED Set LEDs), then blank, then the low nibble, then blank. Bit 0x12 (set when the keyboard answers command 0xAF with 0xFE) swaps LED bits 1 and 2 for a different keyboard type.
Factory mode (B.7): report_error_on_printer_port writes 0x77 to 0x7F2F/0x7FAF (printer data) and pulses 0x7F2D/0x7FAD 08 -> 09 -> 08 (strobe on bit 0), then halts.
selftest_next_group also shows the new group number on the LEDs (or on the printer port in factory mode) as a progress indicator."#, tags=["selftest"], fields={}, links=[]))
set_note(address=CODE:0x74D72..0x74D73, note=Note(id="0000000000000V35TW1CREA9AN", content="Blitter command bit 6 (0x40): after draw_cell_at_column drew a one-cell (0x7F46=0xFF) double-width glyph with 0x9C/0xBC (left half), an odd column (PSW.5) re-issues the command | 0x40 (0xDC/0xFC) to draw the glyph's right half into the cell. Same at 0x74E4F in calc_move_right.", tags=[], fields={}, links=[]))
set_note(address=CODE:0x2CFE2..0x2D021, note=Note(id="0000000000000V3CNN156R2JJQ", content=r#"Stack spill and restore. b2_save_stack_to_xdata pops everything above SP 0x7F (at most 0x20 bytes) into XDATA 0x7412+, with the count at 0x7411. b2_restore_stack_from_xdata pushes it back.
The restore only works because XDATA reads are pipelined (each MOVX read returns the byte fetched by the previous read). It does one throw-away read at 0x7411+count, then reads downward, so every byte arrives one step late and lands in the right place. The emulator must model this, or the stack ends up one byte short and a RET goes wrong. This is also why the firmware reads nearly all XDATA twice ("MOVX; NOP; MOVX"). Only the live registers 0x7F80-0x7FFF answer directly."#, tags=["emulator", "hw"], fields={}, links=[]))
set_note(address=CODE:0x2CC5F..0x2CC78, note=Note(id="0000000000000V3TA7VKA54CSP", content="Key station number (1-0x85) -> internal key index through the table at 0xD20B (indexed from 1, so data starts at 0xD20C). Inverse of 0xD291. Used by DECPFK and related key-definition parsers.", tags=["keyboard"], fields={}, links=[]))
set_note(address=CODE:0x72672..0x726AA, note=Note(id="0000000000000V8G79SHY3HV37", content=r#"Comm receive is DMA-based. Each channel writes received bytes into a ring of pages in low XDATA: +7 = base page (0x28/0x40/0x58 for channels 1/2/3), +8 = page mask (0xFC = 4 pages). Offsets start at 1 when the channel is programmed. The live register at +0xA (0x7FF5 ch1, 0x7F9B ch2, 0x7FEA ch3) has bit 6 = byte received. Writing 0x08 there acknowledges one byte, and the firmware reads the data itself with MOVX @R0 (P2 = page).
Mode register +0 bit 5 = internal loopback. The self-test sets modes 0x20-0x3D; normal setup uses 0x01. Register offsets for ch1/ch3: +0 mode, +1 baud, +2 enable, +3 TX, +4 (0xFB), +5 status, +6, +7 buffer page, +8 buffer mask, +9 modem control, +0xA receive status. Channel 2 skips 0x7F17, so its +7..+0xA sit at 0x18..0x1B. The modem-status words at 0x2C00/0x4400/0x5C00 sit just after each buffer."#, tags=["comm", "hw"], fields={}, links=[]))
set_note(address=CODE:0x71C01..0x71C48, note=Note(id="0000000000000V9MFPZDQEYA74", content="Parallel loopback test, mode step (byte mode): 0x7F2A = 0x01, data 0x7F2F = 0x01, 0x7F2B = 0x80, wait, read 0x7FAC. Bit 2 set = not ready: write 0x0C to 0x7FAC, wait, retry (5 tries, then error bit 0x02 in IDATA 0x73). Otherwise the low nibble must be 0x0A. The nibble-mode copy at 0x71C48 writes data 0x00 and expects 0x09. 0x00 and 0x01 are the IEEE 1284 extensibility codes for nibble and byte mode, and bit 1 differs as 1284's XFlag would, so 0x7F2B bit 7 probably starts a 1284 negotiation and 0x7FAC reports its result; not confirmed. Sequence per pattern (0x71B4E-0x71BE3): 0x7F2B = 0x40, INIT pulse, ring set up (256 or 1024 bytes), 0x71CE9 sends that many incrementing bytes forward with strobes (waits for 0x7FAE bit 1 clear, then bits 4 and 5 after each strobe), this step, then 0x71D70 reads the same bytes back from the ring and compares. A passive plug cannot hold 1024 bytes, so the controller must loop the forward data into the receive ring in this mode. Byte mode for patterns 0x55/0xAA, nibble mode for 0x30/0xFF. DECTST test 10.", tags=["hw", "printer", "selftest"], fields={}, links=[]))
set_note(address=CODE:0x618DB..0x61904, note=Note(id="0000000000000VFT3Y0HVD1DD2", content="Font slot R0 (first glyph column in each 0x80-byte font line): main font (0x74 = 0) -> 0 for the upper window's session (or in Set-Up), 8 for the lower window's session in a split, none if the session is not on screen. Alternate font (0x74 != 0) -> session x 16 (session 1 = columns 16-31, 2 = 32-47, 3 = 48-63, 4 = 64-79). R1 = 0x50 + R0/2 is the matching extra-bits column. Glyph blits reach the alternate font with attribute bits 1-0 = 1 (first 8 columns) or 2 (second 8), and the hardware takes the session from 0x7F32 bits 2-1 (0 = session 4). Verified in the emulator: DEC Technical (CD = 1) and the Special Graphics checkerboard (CD = 2) render correctly in a split with session 1 at 132 columns and session 2 at 80, whose alternate fonts differ in all 256 glyphs.", tags=["font", "hw"], fields={}, links=[]))
set_note(address=CODE:0x712FA..0x713C9, note=Note(id="0000000000000VJ859VJ3F05CE", content=r#"INT1 serves three UART-like comm channels. Each channel is an 11-byte register block. The block bases are 0x7F6B (state byte 0x0D), 0x7F10 (state 0x0E) and 0x7F60 (state 0x0F).
Offsets from the base: +3 transmit data (XON 0x11 and XOFF 0x13 are written to 0x7FEE), +5 status on read (bit 1, bit 2 and bit 3 each call a handler) and the state low nibble on write, +6 written with 0x38 or 0x00, +0xA command (the handler writes 0x06).
Every write goes to both 0x7Fxx and 0x7Fxx+0x80. Status reads use only the +0x80 copy.
The handler reads 0x740D on entry and again on exit. Every ISR does this with its own address (0x740E INT0, 0x740F Timer 0), so it may be an interrupt acknowledge."#, tags=["comm", "hw"], fields={}, links=[]))
set_note(address=CODE:0x70100..0x701A0, note=Note(id="0000000000000VJAGFGACGWJP2", content=r#"INT0 serves the PS/2 keyboard and a second source, probably the frame/vertical retrace.
0x7FFB status: bit 1 means a byte has arrived. Read it at 0x7FFA, then write 0x02 to 0x7FFB to acknowledge. Bits 2-3 are errors: write 0x0E to 0x7FFB, then send 0xFE (Resend) through 0x7FF8. Replies 0xFA (ACK) and 0xFE (Resend) are handled.
Bit 4 is the second source. Write 0x10 to 0x7FFB to acknowledge it. It then copies lower-half registers to the upper half (0x7F31->0x7FB1, 0x7F35->0x7FB5, 0x7F38..3A->0x7FB8..BA), reading each one twice with a NOP between. This looks like a video update applied once per frame."#, tags=["hw", "keyboard", "video"], fields={}, links=[]))
set_note(address=CODE:0x717DE..0x717DF, note=Note(id="0000000000000VNVKR76JVJP9V", content="Blitter command write: R5 is 0x9D (entry blit_fb_copy_up 0x71784) or 0x8D (entry blit_fb_copy_down 0x71788). No other entry into the body (checked every LJMP/LCALL/AJMP/ACALL in bank 7).", tags=[], fields={}, links=[]))
set_note(address=CODE:0x6E5..0x73A, note=Note(id="0000000000000VQQSVSDZNY18V", content="Soft-font cell draw (attribute bits 1-0 = 3, reached from bank 7 0x756D6). Writes the cell attribute to 0x7F4D, the glyph index to 0x7F40, block 0x12 (or 0x06 when bit 0x17 is clear) to 0x7F42, and issues blit 0xBC. The soft font holds 80 glyph columns per 16-line block, extra bits at 0x50 + column/2.", tags=["blitter", "font", "video"], fields={}, links=[]))
set_note(address=CODE:0x36BED..0x36C23, note=Note(id="0000000000000VRWVV2JZJTWTH", content="Framed layout step 0x0A: 0x7F35 = layout parameter - 1 = the height - 1 (scan lines) of the trailing filler row, then appends that row (flag 0x40, 0xC0 in window 2) pointing at a free stored row from the pool at 0x7019 (0xB76C; 0xD7 for format 1) and saves its entry at XDATA 0xB86B. Each horizontal rule (flag bit 5 or 4) takes one scan line, so rows + rules + 0x7F35 + 1 = 480 in every framed layout tried (one window 13, split 11, 36 lines 7, 48 lines 5, mixed split 9).", tags=["hw", "video"], fields={}, links=[]))
set_note(address=CODE:0x2796..0x27D6, note=Note(id="0000000000000VWQZHFSS73KGM", content="Port service (entries for port 3, 2, 1 at 0x2779, 0x278C, 0x2796). Skips while the port's transmit is busy (IDATA 0x53 bit n). Sets IDATA 0x74 = port, maps the port block through window B (sub_08D2), reads port + 0x67 through the window (0x1467). Bit 4 = attached; bits 3-0 = session, stored in IDATA 0x61. Then it moves the session's keyboard data to the port (0x2905/0x290E).", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x70042..0x70075, note=Note(id="0000000000000WGKQPRC4NTNA6", content=r#"ROM cartridge detection. The code writes 0x80 to the RAM page register (0x7F36), which maps the cartridge into XDATA, and compares XDATA 0x0030-0x0039 with rom_signature (AA 55 "%2DEC520").
On a match, cartridge_found_switch_rom runs CLR P3.0, which appears to switch code fetches to the cartridge. It then resets SP and jumps straight into selftest_keyboard, because the code underneath has changed. The ROM checksum test then covers the cartridge. If that fails with P3.0 clear, cartridge_checksum_failed sets P3.0 again (back to internal ROM), sets 0x59 bit 1 ("ROM Cartridge Error - 10") and repeats the ROM test.
For the emulator: with no cartridge, the signature compare must fail, and P3.0 must stay 1."#, tags=["cartridge", "hw", "selftest"], fields={}, links=[]))
set_note(address=CODE:0x740BF..0x740C0, note=Note(id="0000000000000WK22EZZB5XYWM", content=r#"Calculator key dispatcher: A = key index * 3, JMP @A+DPTR into the LJMP table at 0x740C3. Entry 19 (0x740FC) = calc_move_left, entry 20 (0x740FF) = calc_move_right. Called from 0x73F68/0x73FA8. Operator glyphs " +-x/" at 0x740A8."#, tags=[], fields={}, links=[]))
set_note(address=CODE:0x6198A..0x619E6, note=Note(id="0000000000000WX60Q4T1QR500", content="Unpack one glyph. For each line: the 8-bit glyph byte goes to column R0 (MOVX @R0), and the 2 extra bits (low 2 bits of the second packed byte, IDATA 0x7B) go to column R1 = 0x50 + R0/2: bits 1-0 when bit 0x38 is clear (even column), bits 5-4 when set (odd column). R0/R1 step 0x80 per line (P2 carries). Bit 0 of the pair is pixel 8, next to glyph bit 7, so a glyph is 10 pixels wide. After the glyph, P2 skips (0x11 - lines) / 2 pages to the next 16-line block.", tags=["font", "video"], fields={}, links=[]))
set_note(address=CODE:0x72C0D..0x72C1A, note=Note(id="0000000000000X8CC2ZAFZS16P", content=r#"Self-test overview. B holds the mode flags for the whole run: 0x52 on power-up, 0x53 from reset_entry_alt (re-run from a script/menu), 0xB6 in factory mode. 0x74 holds more test-select bits (0x10 at power-up, 0xF0 in factory mode).
Order: internal RAM (test_internal_ram) -> check_rom_xdata_alias -> keyboard (kbd_reset_and_identify) -> group 1 ROM checksums (test_rom_checksums) -> group 2 RAM (test_ram) -> hw setup, register table, test_dma, dma_clear_ram, save_ram_config -> group 3 via far_b0_AA67 (bank 0, not mapped here) -> selftest_finish runs the selected comm and printer tests -> far_b0_23CC_main.
0x77 is the current test code: high nibble = group (selftest_next_group rounds it up to the next 0x10), low nibble = step (each test does INC 0x77 first). Codes seen: 0x11-0x18 ROM bank 0-7 checksum, 0x21 RAM data bus, 0x22 RAM address bus, 0x23 RAM bank probe/config. An internal RAM failure reports 0x11 plus 0x77 (set to 0 first).
0x58/0x59 are the non-fatal error flags checked after the tests. 0x58: bit1 ch1 internal loopback, bit2 ch1 modem lines, bit3 ch2 internal, bit4 ch2 modem lines, bit5 ch3 internal, bit6 ch3 modem lines, bit7 keyboard. 0x59: bit0 printer loopback, bit1 ROM test gave up, bit2 printer data test."#, tags=["selftest"], fields={}, links=[]))
set_note(address=CODE:0x73708..0x73739, note=Note(id="0000000000000XDFFW7440HM07", content="Parallel printer port setup: control 0x7F2D = 0x08, receive ring page mask 0x7F29 = 0xFF (one page), ring base page 0x7F28 = 0x75, receive command 0x7F2A = 0x01, XDATA 0x7436 = 1, then bank 0 0x3705 pulses INIT (0x7F2D = 0x0C then 0x08). The ring is never read in normal operation (page 0x75 also holds variables) and 0x7F2B is only written by the self-test, so reverse (printer-to-terminal) transfer is armed but unused.", tags=["hw", "printer"], fields={}, links=[]))
set_note(address=CODE:0x20D1..0x216F, note=Note(id="0000000000000XDNE3CTGPX6S4", content="comm1 transmitter empty. Needs IDATA 0x53 bit 4. Holds while 0x7FF4 bit 1 is set (transmit stopped), or while modem status 0x7FDB bit 6 is set and port setting 0x2C00 bit 2 is on. Sends XON (0x11) or XOFF (0x13) first when IDATA 0x0D bit 7/6 asks for one, else the next byte from the transmit queue at 0x2E00 (read index 0x2D08, count 0x2D09) to 0x7FEE. When the queue empties it clears 0x53 bit 0; at the end it clears the transmit interrupt enable (0x0D bit 3).", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x2351..0x236E, note=Note(id="0000000000000XEEJAFWZ4M10R", content="Loads a port's flow settings into B: B.1 = port+0 bit 0 (receive XON/XOFF), B.2 = port+0 bit 1 (receive DTR), B.3 = port+2 bit 0 (flow control threshold High). comm_resume_point (0x351B) and comm_xoff_threshold (0x231F) turn B.3 into the resume point (0x02 = 32 bytes, 0x08 = 128) and XOFF threshold (0x04 = 64, 0x30 = 768), matching manual Table 9-3. Verified: DECSFC CSI 1;2;1;2*s writes 0x7FD9 = 08 and 0x7FF1 = 30.", tags=["comm"], fields={}, links=[]))
set_note(address=CODE:0x72B49..0x72B60, note=Note(id="0000000000000XTC9HHMQY69G1", content="Copy command: 0x13 normally, 0x03 when bit 0x3C is set. 0x13 copies upward (and overlapping copies one or two bytes up are used as fills). 0x03 copies downward from the given last addresses; bank 5 0x5B790 uses it to shift the row descriptor, rendition and 0xCF21 tables up when inserting a page. Blitter addresses are 32KB block : 15-bit offset, block = page (IDATA 0x7E) * 2 + DPH bit 7, the same blocks as 0x7F36. Low XDATA is block 4, so XDATA 0x0000-0xFFFF with 0x7F36 = 5 is one 64KB page to the firmware.", tags=["blitter", "memory"], fields={}, links=[]))
set_note(address=CODE:0x72743..0x72800, note=Note(id="0000000000000Y05ENGCXKPAZ0", content=r#"Keyboard detection. kbd_reset_and_identify waits for BAT 0xAA, sends 0xFF (Reset) and expects FA then AA, then 0xF2 (Identify) and expects FA AB xx, then sends 0xAF. A reply of 0xFE sets bit 0x12.
If that fails, kbd_line_loopback_test toggles 0x7F30 bit 6 (0x60 -> 0x20) and drives 0x7FF9 bit 6, then checks that 0x7FFB bits 0 and 5 (0x21) follow, 11 times. If they do, a loopback plug sits on the keyboard port: it returns C=1, A=0, and selftest_keyboard then looks for a comm loopback (sends 0xAA on channel 1 through 0x7F6E and waits for 0x7FF5 bit 6). An echo selects the factory test set (B=0xB6). A timeout goes to factory_loopback_mode.
A plain failure returns C=1, A=1 and sets 0x58 bit 7 (keyboard error)."#, tags=["keyboard", "selftest"], fields={}, links=[]))
set_note(address=CODE:0x72F0B..0x73178, note=Note(id="0000000000000Y962PZN041237", content=r#"RAM tests. External RAM appears through a 32 KB window at XDATA 0x8000-0xFFFF. 0x7F36/0x7FB6 selects the page. restore_ram_page writes the normal value: 0x11, or 0x05 when bit 0x17 is set.
test_ram_data_bus: walking ones at 0x8000 plus 0x55/0xAA. test_ram_address_bus: writes at 0x8000|(1<<n) for each address line.
probe_ram_bank runs 4 times (R3 = 0x00, 0x0C, 0x18, 0x24). It writes a page tag at 0x8055/0x80AA of each page and reads them back to find which pages exist and whether they alias. It stores 2 bytes per bank in IDATA 0xE0-0xE7: 0x0F/0x00 = present, 0xFF/0xFF = wraps (smaller part), 0x00/0x00 = absent.
decode_ram_config turns those bytes into bit flags 0x17 and 0x39-0x3E (bank present / bank size). save_ram_config copies 0xE0-0xE7 to XDATA 0xB900, and load_ram_config copies them back."#, tags=["ram", "selftest"], fields={}, links=[]))
set_note(address=CODE:0x73B24..0x73B70, note=Note(id="0000000000000YA7BAFWM1HVVB", content=r#"Blitter commands seen (written to 0x7F49/0x7FC9; P1.0 high = ready). Addresses are linear into video/system DRAM, with window A/B unit u = u*0x800 and 0x7F36 page p = p*0x8000.
0x13 and 0x03: copy count bytes from src to dst.
0x9E: fill count bytes at dst with 0x7FCD. video_init clears video memory with 32 of these (0x7FC4 steps by 8, count 0xF84).
0x9C: used by b3_blit_char_cells with 0x7F43 = column, 0x7F40/0x7F41 = R2/R3, 0x7F4D = character, 0x7F4E = attribute/rendition (from 0x08D6), count from bank 0 sub_CFA2. Probably fills character/attribute pairs. Not yet confirmed.
The count register holds 0x10000 - count."#, tags=["blitter", "hw", "video"], fields={}, links=[]))
set_note(address=CODE:0x811..0x81A, note=Note(id="0000000000000YHEQNBG7DJBGB", content="Load DPTR from the 16-bit pointer at XDATA DPTR, relying on the one-behind read latch: read 1 starts the low-byte fetch, INC DPTR, read 2 returns the low byte (and fetches the high byte), MOV DPL,A, read 3 (at an unrelated address) returns the high byte. Proof that XDATA reads return the previous access's data rather than being a timing wait state. With unpipelined reads the boot diverges at the first call (bank 3 0x2D37).", tags=["hw", "memory"], fields={}, links=[]))
set_note(address=CODE:0x249C8..0x249E4, note=Note(id="0000000000000YQ0GEXWR6FDAX", content="Power-up Set-Up escape: with no modifiers, key index 0x61 (F3) always runs Set-Up while XDATA 0x7349 is 0. 0x7349 is 0 after reset and becomes 0xFF on the first ordinary key (0x27D7C). This works on the PC keyboard in PC-style mode, where F3 is otherwise a plain function key, and even after DECLFKC disables Set-Up (the Set-Up handler 0x26C0E also skips its DECLFKC check while 0x7349 is 0). Inside Set-Up (bit 0x20), F3 also exits while 0x734A is not 0xFF. Verified: CSI 3;3*} then F3 enters Set-Up; typing a key first stops it.", tags=["hidden", "keyboard"], fields={}, links=[]))
set_note(address=CODE:0x592D0..0x5930C, note=Note(id="0000000000000YTYEZTVVMAD11", content="Set-Up menu row drawing. The first byte of the row buffer goes to 0x7F4D/0x7FCD before the 0x9C glyph blits of that row: 0x20 = selected item (reverse), 0x80 = unavailable item, 0x00 = normal. The glyph attribute 0x7F41 stays 0, so the blitter must combine 0x7FCD with the cell attribute.", tags=["setup", "video"], fields={}, links=[]))
set_note(address=CODE:0x3AF4..0x3C4F, note=Note(id="0000000000000Z6VHRSVCX9S4C", content=r#"NVR is a 24C16-style I2C EEPROM (2KB in eight 256-byte blocks), bit-banged on P1.1 = SCL and P1.2 = SDA (open drain). The VT420 used a 3-wire ER5911 on the DUART instead.
Control byte = 0xA0 | (address bits 10-8) << 1 | R/W (i2c_send_control). A read sends the word address, a repeated START, then clocks bytes in with ACK, NACKs the last byte and sends STOP.
Blocks: R3/R4 = NVR address, R1/R2 = count, DPTR = RAM copy, R5 = checksum seed. A block is valid when (seed + bytes + checksum byte) & 0xFF == 0.
Global blocks: 0x000 (0x19 bytes, to 0x7100), 0x03A (0x2A, to 0x713B), 0x065 (0x1F, to 0x7166), 0x085 (4, to 0x7186). Sessions 1-4 start at 0x08A/0x102/0x17A/0x1F2 (table at 0x8EB2, 0x78 bytes each): +0 (0x24, to 0x0D00), +0x46 (0x11, to 0x0D46), +0x58 (0x1F, to 0x0D58). More blocks follow from 0x26A.
nvr_check_all sets XDATA 0x91A9 = 0xFF on a bad block, and the firmware quietly uses defaults. 0x58 bit 0 ("NVR Error - 1") means the bus itself failed (no ACK, SDA stuck low). nvr_save_all (0x8C22) writes every block. The emulator's factory image (roms/vt520/nvr-factory.bin) was made by calling it after defaults loaded."#, tags=["hw", "nvr"], fields={}, links=[]))
set_note(address=CODE:0x3791F..0x37B8F, note=Note(id="0000000000000ZFWDER7H4FNQ8", content=r#"Self-test result report, called from the main entry (bank 0:0x23CC). If 0x7014 bit 0 is set, the keyboard error bit is ignored. Each set bit in 0x58 (R0=0..7) and 0x59 (R0=8..) selects a message from selftest_message_ptrs (little-endian pointers into bank 3). Each message is (row, column, length, text).
0x58: bit0 NVR Error - 1, bit1 Comm 1 Port Data - 2, bit2 Comm 1 Port Controls - 3, bit3 Comm 2 Data - 4, bit4 Comm 2 Controls - 5, bit5 Comm 3 Data - 6, bit6 Comm 3 Controls - 7, bit7 Keyboard - 8. 0x59: bit0 Parallel Port - 9, bit1 ROM Cartridge - 10, bit2 Parallel Port Test Module - 11.
With no errors it draws the startup screen, including "Selftest OK" in the selected language (strings from 0x37D96).
The screen writer stores two bytes per cell, attribute then character, through MOVX @R1 with P2 as the high address byte. The page comes from bank 0:0xACE8."#, tags=["selftest", "video"], fields={}, links=[]))
set_note(address=CODE:0xBC9B..0xBCA6, note=Note(id="0000000000000ZR3SFB1CR0NZT", content="Video format register 0x7F32. Bits 7-4: underline scan line (0xE, 0x9, 0x7 for 24, 36, 48 lines per screen). Bit 3: 132 columns. 0x7F38 (0xBCC9, 0xBEE2): bits 3-0 = scan lines per row - 1 (0xF, 0x9, 0x7), bit 4 = 132 columns, bit 5 = Set-Up on screen, bit 6 = light background. Found by changing Set-Up > Display.", tags=["setup", "video"], fields={}, links=[]))
set_note(address=CODE:0x32130..0x32260, note=Note(id="0000000000000ZVBFN2Q2ZT13E", content="Screen savers, run once a second. XDATA 0x74D9/0x74DA counts idle seconds (cleared by sub_32350 on key 0x2B/0x2F or host activity). CRT saver: 0x7012 bits 4-2 index the table at 0x32374 (300, 900, 1800, 3600 s; 4 = never); on a match 0x3215C sets 0x7F31 bit 2 (blank) and waits for a key. Energy saver (0x7012 bits 7-6: 5/15/30 min/never): 0x3220C saves 0x7F52 in 0x74E1, sets 0x7F52 = 0x88, sets 0x7F31 bits 2, 4, 5, waits (0x32283), clears bit 4. Wake (0x3223F): restore 0x7F52, set bit 4, clear bit 5, then 0x321B5 clears bits 2, 4, 5. Guess: bits 4/5 = hsync/vsync off (DPMS).", tags=["crt", "video"], fields={}, links=[]))
set_note(address=CODE:0x61846..0x619E6, note=Note(id="0000000000000ZX2FB81VWKCF0", content=r#"Font unpack (packed fonts in bank 6 ROM around 0x2500-0x5B00). Each glyph starts with an 8-bit line mask (8 lines per mask byte, refilled for the rest of the glyph). A set bit reads 2 bytes: the 8 pixel bits and 2 extra bits (low 2 bits of the second byte) for the 10-pixel-wide cell. A clear bit repeats the previous line. This is the VT420's 8+2-bit glyph format, with line-repeat compression added.
Output goes through the 0x8000 window with 0x7F36 = 2 and 3 (64KB pages, linear 0x20000/0x30000). Layout: column-major with a 0x80-byte line stride. Glyphs are 16 lines (0x800 bytes) tall and stacked 16 per column. Character c sits in page 2 + ((c >> 4) & 1), block c & 15, column slot + (c >> 5). The extra 2-bit values go in columns 0x50 + slot/2, four characters per byte (bit 0x38 picks the nibble).
Bit 0 of each pixel byte is the leftmost pixel."#, tags=["font", "video"], fields={}, links=[]))
